name: CI

on: [push]

jobs:
  # does Mybuilds processing and provides mk/.cache to other jobs
  buildgen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make confload-test/buildgen
      - run: make -j $(nproc) buildgen
      - name: compress
        run: |
          mkdir mk-cache
          tar zcf mk-cache/archive.tar.gz mk/.cache
      - uses: actions/upload-artifact@v1
        with:
          name: mk-cache
          path: mk-cache

  ci:
    needs: buildgen
    runs-on: ubuntu-16.04 # Embox NFS write test fails with ubuntu 18.04: "RPC: Can't decode result"
    strategy:
      fail-fast: false
      matrix:
        template:
          - aarch64/qemu
          - arm/qemu
          - arm/stm32f4-discovery
          - x86/qemu
          - x86/smp
          - x86/user_apps
          - x86/qt-app
          - x86/test/lang
          - x86/test/net
          - x86/test/fs
          - x86/test/units
          - x86/test/packetdrill
          - x86/test/qt-vnc
          - sparc/qemu
          - mips/qemu
          - ppc/qemu
          - microblaze/qemu
          - usermode86/debug
    container:
      image: embox/emdocker-test
      options: --privileged -v /:/host
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v1
        with:
          name: mk-cache
      - name: unpack mk-cache
        run: |
          tar zxf mk-cache/archive.tar.gz
          scripts/continuous/touch-mk-cache.sh
      - run: chroot /host modprobe nfsd
        if: matrix.template == 'x86/test/fs'
      - run: ./scripts/continuous/prepare.sh ${{matrix.template}}
      - run: make confload-${{matrix.template}}
      - run: make -j $(nproc)
      - run: ./scripts/continuous/run.sh ${{matrix.template}}
